#!/usr/bin/env python3
"""
07_add_name_ja.py
name_ja（カタカナ一般名）が欠落している薬に日本語名を補完するパッチスクリプト。
冪等: 既に name_ja がある薬はスキップ。

戦略:
1. 大規模 英名→カタカナ 辞書（手動キュレーション）
2. 接尾辞ベースの自動変換ルール
3. graph.json / graph-light.json の両方をパッチ
"""

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR.parent / "data"
GRAPH_FILES = [
    DATA_DIR / "graph" / "graph.json",
    DATA_DIR / "graph" / "graph-light.json",
]

# ============================================================
# 1. 英名→カタカナ 辞書（約800語）
# ============================================================
MANUAL_JA = {
    # --- 鎮痛・解熱・抗炎症 ---
    "Acetaminophen": "アセトアミノフェン",
    "Aspirin": "アスピリン",
    "Loxoprofen": "ロキソプロフェン",
    "Ibuprofen": "イブプロフェン",
    "Diclofenac": "ジクロフェナク",
    "Celecoxib": "セレコキシブ",
    "Meloxicam": "メロキシカム",
    "Naproxen": "ナプロキセン",
    "Indomethacin": "インドメタシン",
    "Etodolac": "エトドラク",
    "Piroxicam": "ピロキシカム",
    "Mefenamic acid": "メフェナム酸",
    "Flurbiprofen": "フルルビプロフェン",
    "Sulindac": "スリンダク",
    "Tiaprofenic acid": "チアプロフェン酸",
    "Zaltoprofen": "ザルトプロフェン",

    # --- オピオイド ---
    "Morphine": "モルヒネ",
    "Oxycodone": "オキシコドン",
    "Fentanyl": "フェンタニル",
    "Tramadol": "トラマドール",
    "Codeine": "コデイン",
    "Hydromorphone": "ヒドロモルフォン",
    "Buprenorphine": "ブプレノルフィン",
    "Methadone": "メサドン",
    "Tapentadol": "タペンタドール",
    "Pentazocine": "ペンタゾシン",
    "Pethidine": "ペチジン",
    "Naloxone": "ナロキソン",
    "Naltrexone": "ナルトレキソン",

    # --- 神経・疼痛 ---
    "Pregabalin": "プレガバリン",
    "Gabapentin": "ガバペンチン",
    "Mirogabalin": "ミロガバリン",
    "Duloxetine": "デュロキセチン",
    "Amitriptyline": "アミトリプチリン",

    # --- 降圧薬 ARB ---
    "Candesartan": "カンデサルタン",
    "Olmesartan": "オルメサルタン",
    "Valsartan": "バルサルタン",
    "Telmisartan": "テルミサルタン",
    "Losartan": "ロサルタン",
    "Irbesartan": "イルベサルタン",
    "Azilsartan": "アジルサルタン",
    "Eprosartan": "エプロサルタン",

    # --- 降圧薬 ACE阻害 ---
    "Enalapril": "エナラプリル",
    "Lisinopril": "リシノプリル",
    "Ramipril": "ラミプリル",
    "Perindopril": "ペリンドプリル",
    "Captopril": "カプトプリル",
    "Imidapril": "イミダプリル",
    "Temocapril": "テモカプリル",
    "Benazepril": "ベナゼプリル",
    "Quinapril": "キナプリル",
    "Trandolapril": "トランドラプリル",

    # --- 降圧薬 Ca拮抗 ---
    "Amlodipine": "アムロジピン",
    "Nifedipine": "ニフェジピン",
    "Diltiazem": "ジルチアゼム",
    "Verapamil": "ベラパミル",
    "Benidipine": "ベニジピン",
    "Azelnidipine": "アゼルニジピン",
    "Cilnidipine": "シルニジピン",
    "Nicardipine": "ニカルジピン",
    "Felodipine": "フェロジピン",
    "Barnidipine": "バルニジピン",
    "Manidipine": "マニジピン",
    "Nitrendipine": "ニトレンジピン",
    "Efonidipine": "エホニジピン",

    # --- β遮断薬 ---
    "Bisoprolol": "ビソプロロール",
    "Carvedilol": "カルベジロール",
    "Atenolol": "アテノロール",
    "Propranolol": "プロプラノロール",
    "Metoprolol": "メトプロロール",
    "Celiprolol": "セリプロロール",
    "Nebivolol": "ネビボロール",
    "Labetalol": "ラベタロール",

    # --- 利尿薬 ---
    "Furosemide": "フロセミド",
    "Tolvaptan": "トルバプタン",
    "Spironolactone": "スピロノラクトン",
    "Eplerenone": "エプレレノン",
    "Hydrochlorothiazide": "ヒドロクロロチアジド",
    "Trichlormethiazide": "トリクロルメチアジド",
    "Indapamide": "インダパミド",
    "Torasemide": "トラセミド",
    "Azosemide": "アゾセミド",

    # --- 強心・抗不整脈 ---
    "Digoxin": "ジゴキシン",
    "Amiodarone": "アミオダロン",
    "Flecainide": "フレカイニド",
    "Pilsicainide": "ピルシカイニド",
    "Lidocaine": "リドカイン",
    "Procainamide": "プロカインアミド",
    "Disopyramide": "ジソピラミド",
    "Mexiletine": "メキシレチン",
    "Propafenone": "プロパフェノン",
    "Bepridil": "ベプリジル",
    "Nicorandil": "ニコランジル",
    "Isosorbide": "イソソルビド",
    "Nitroglycerin": "ニトログリセリン",

    # --- スタチン ---
    "Atorvastatin": "アトルバスタチン",
    "Rosuvastatin": "ロスバスタチン",
    "Pravastatin": "プラバスタチン",
    "Pitavastatin": "ピタバスタチン",
    "Simvastatin": "シンバスタチン",
    "Fluvastatin": "フルバスタチン",
    "Lovastatin": "ロバスタチン",

    # --- 脂質異常 ---
    "Ezetimibe": "エゼチミブ",
    "Fenofibrate": "フェノフィブラート",
    "Bezafibrate": "ベザフィブラート",
    "Pemafibrate": "ペマフィブラート",
    "Clofibrate": "クロフィブラート",

    # --- 抗凝固 ---
    "Warfarin": "ワルファリン",
    "Heparin": "ヘパリン",
    "Edoxaban": "エドキサバン",
    "Rivaroxaban": "リバーロキサバン",
    "Apixaban": "アピキサバン",
    "Dabigatran": "ダビガトラン",
    "Enoxaparin": "エノキサパリン",
    "Fondaparinux": "フォンダパリヌクス",
    "Danaparoid": "ダナパロイド",

    # --- 抗血小板 ---
    "Clopidogrel": "クロピドグレル",
    "Prasugrel": "プラスグレル",
    "Ticagrelor": "チカグレロル",
    "Cilostazol": "シロスタゾール",
    "Ticlopidine": "チクロピジン",
    "Sarpogrelate": "サルポグレラート",

    # --- 消化器 PPI/P-CAB ---
    "Omeprazole": "オメプラゾール",
    "Lansoprazole": "ランソプラゾール",
    "Rabeprazole": "ラベプラゾール",
    "Esomeprazole": "エソメプラゾール",
    "Vonoprazan": "ボノプラザン",
    "Famotidine": "ファモチジン",
    "Ranitidine": "ラニチジン",
    "Cimetidine": "シメチジン",
    "Nizatidine": "ニザチジン",
    "Lafutidine": "ラフチジン",

    # --- 消化器 その他 ---
    "Rebamipide": "レバミピド",
    "Teprenone": "テプレノン",
    "Irsogladine": "イルソグラジン",
    "Sucralfate": "スクラルファート",
    "Misoprostol": "ミソプロストール",
    "Mosapride": "モサプリド",
    "Domperidone": "ドンペリドン",
    "Metoclopramide": "メトクロプラミド",
    "Itopride": "イトプリド",
    "Trimebutine": "トリメブチン",
    "Lubiprostone": "ルビプロストン",
    "Linaclotide": "リナクロチド",
    "Elobixibat": "エロビキシバット",
    "Loperamide": "ロペラミド",
    "Ondansetron": "オンダンセトロン",
    "Granisetron": "グラニセトロン",
    "Palonosetron": "パロノセトロン",
    "Aprepitant": "アプレピタント",
    "Fosaprepitant": "ホスアプレピタント",

    # --- 糖尿病 ---
    "Metformin": "メトホルミン",
    "Pioglitazone": "ピオグリタゾン",
    "Glimepiride": "グリメピリド",
    "Glibenclamide": "グリベンクラミド",
    "Gliclazide": "グリクラジド",
    "Voglibose": "ボグリボース",
    "Miglitol": "ミグリトール",
    "Acarbose": "アカルボース",
    "Sitagliptin": "シタグリプチン",
    "Vildagliptin": "ビルダグリプチン",
    "Alogliptin": "アログリプチン",
    "Linagliptin": "リナグリプチン",
    "Teneligliptin": "テネリグリプチン",
    "Saxagliptin": "サキサグリプチン",
    "Trelagliptin": "トレラグリプチン",
    "Empagliflozin": "エンパグリフロジン",
    "Dapagliflozin": "ダパグリフロジン",
    "Canagliflozin": "カナグリフロジン",
    "Ipragliflozin": "イプラグリフロジン",
    "Tofogliflozin": "トホグリフロジン",
    "Luseogliflozin": "ルセオグリフロジン",
    "Semaglutide": "セマグルチド",
    "Liraglutide": "リラグルチド",
    "Dulaglutide": "デュラグルチド",
    "Exenatide": "エキセナチド",
    "Insulin glargine": "インスリン グラルギン",
    "Insulin aspart": "インスリン アスパルト",
    "Insulin lispro": "インスリン リスプロ",
    "Insulin detemir": "インスリン デテミル",
    "Insulin degludec": "インスリン デグルデク",

    # --- 甲状腺 ---
    "Levothyroxine": "レボチロキシン",
    "Methimazole": "チアマゾール",
    "Propylthiouracil": "プロピルチオウラシル",
    "Thiamazole": "チアマゾール",

    # --- 骨粗鬆症 ---
    "Alendronate": "アレンドロン酸",
    "Risedronate": "リセドロン酸",
    "Minodronate": "ミノドロン酸",
    "Zoledronic acid": "ゾレドロン酸",
    "Ibandronate": "イバンドロン酸",
    "Denosumab": "デノスマブ",
    "Teriparatide": "テリパラチド",
    "Raloxifene": "ラロキシフェン",
    "Bazedoxifene": "バゼドキシフェン",
    "Eldecalcitol": "エルデカルシトール",
    "Alfacalcidol": "アルファカルシドール",
    "Calcitriol": "カルシトリオール",

    # --- 睡眠薬・抗不安 ---
    "Zolpidem": "ゾルピデム",
    "Zopiclone": "ゾピクロン",
    "Eszopiclone": "エスゾピクロン",
    "Suvorexant": "スボレキサント",
    "Lemborexant": "レンボレキサント",
    "Ramelteon": "ラメルテオン",
    "Triazolam": "トリアゾラム",
    "Nitrazepam": "ニトラゼパム",
    "Flunitrazepam": "フルニトラゼパム",
    "Brotizolam": "ブロチゾラム",
    "Estazolam": "エスタゾラム",
    "Quazepam": "クアゼパム",
    "Lormetazepam": "ロルメタゼパム",
    "Rilmazafone": "リルマザホン",
    "Diazepam": "ジアゼパム",
    "Alprazolam": "アルプラゾラム",
    "Lorazepam": "ロラゼパム",
    "Etizolam": "エチゾラム",
    "Clonazepam": "クロナゼパム",
    "Bromazepam": "ブロマゼパム",
    "Chlordiazepoxide": "クロルジアゼポキシド",
    "Midazolam": "ミダゾラム",
    "Melatonin": "メラトニン",

    # --- 抗うつ SSRI/SNRI ---
    "Sertraline": "セルトラリン",
    "Escitalopram": "エスシタロプラム",
    "Paroxetine": "パロキセチン",
    "Fluvoxamine": "フルボキサミン",
    "Fluoxetine": "フルオキセチン",
    "Citalopram": "シタロプラム",
    "Mirtazapine": "ミルタザピン",
    "Venlafaxine": "ベンラファキシン",
    "Milnacipran": "ミルナシプラン",
    "Trazodone": "トラゾドン",
    "Nortriptyline": "ノルトリプチリン",
    "Imipramine": "イミプラミン",
    "Clomipramine": "クロミプラミン",
    "Maprotiline": "マプロチリン",

    # --- 抗精神病 ---
    "Haloperidol": "ハロペリドール",
    "Chlorpromazine": "クロルプロマジン",
    "Risperidone": "リスペリドン",
    "Olanzapine": "オランザピン",
    "Quetiapine": "クエチアピン",
    "Aripiprazole": "アリピプラゾール",
    "Brexpiprazole": "ブレクスピプラゾール",
    "Paliperidone": "パリペリドン",
    "Blonanserin": "ブロナンセリン",
    "Perospirone": "ペロスピロン",
    "Clozapine": "クロザピン",
    "Sulpiride": "スルピリド",
    "Tiapride": "チアプリド",
    "Lithium": "リチウム",

    # --- 抗てんかん ---
    "Carbamazepine": "カルバマゼピン",
    "Lamotrigine": "ラモトリギン",
    "Levetiracetam": "レベチラセタム",
    "Phenytoin": "フェニトイン",
    "Phenobarbital": "フェノバルビタール",
    "Topiramate": "トピラマート",
    "Zonisamide": "ゾニサミド",
    "Lacosamide": "ラコサミド",
    "Perampanel": "ペランパネル",
    "Clobazam": "クロバザム",
    "Rufinamide": "ルフィナミド",
    "Stiripentol": "スチリペントール",

    # --- パーキンソン ---
    "Levodopa": "レボドパ",
    "Pramipexole": "プラミペキソール",
    "Ropinirole": "ロピニロール",
    "Rotigotine": "ロチゴチン",
    "Entacapone": "エンタカポン",
    "Selegiline": "セレギリン",
    "Rasagiline": "ラサギリン",
    "Safinamide": "サフィナミド",
    "Istradefylline": "イストラデフィリン",
    "Droxidopa": "ドロキシドパ",
    "Trihexyphenidyl": "トリヘキシフェニジル",
    "Biperiden": "ビペリデン",
    "Amantadine": "アマンタジン",

    # --- 認知症 ---
    "Donepezil": "ドネペジル",
    "Memantine": "メマンチン",
    "Galantamine": "ガランタミン",
    "Rivastigmine": "リバスチグミン",

    # --- 片頭痛 ---
    "Sumatriptan": "スマトリプタン",
    "Rizatriptan": "リザトリプタン",
    "Zolmitriptan": "ゾルミトリプタン",
    "Eletriptan": "エレトリプタン",
    "Naratriptan": "ナラトリプタン",
    "Erenumab": "エレヌマブ",
    "Galcanezumab": "ガルカネズマブ",
    "Fremanezumab": "フレマネズマブ",
    "Valproic acid": "バルプロ酸",

    # --- 呼吸器 ---
    "Montelukast": "モンテルカスト",
    "Pranlukast": "プランルカスト",
    "Zafirlukast": "ザフィルルカスト",
    "Fluticasone": "フルチカゾン",
    "Budesonide": "ブデソニド",
    "Beclomethasone": "ベクロメタゾン",
    "Ciclesonide": "シクレソニド",
    "Mometasone": "モメタゾン",
    "Salbutamol": "サルブタモール",
    "Salmeterol": "サルメテロール",
    "Formoterol": "ホルモテロール",
    "Indacaterol": "インダカテロール",
    "Vilanterol": "ビランテロール",
    "Tiotropium": "チオトロピウム",
    "Glycopyrronium": "グリコピロニウム",
    "Umeclidinium": "ウメクリジニウム",
    "Theophylline": "テオフィリン",
    "Aminophylline": "アミノフィリン",
    "Carbocisteine": "カルボシステイン",
    "Ambroxol": "アンブロキソール",
    "Dextromethorphan": "デキストロメトルファン",
    "Codeine": "コデイン",
    "Ephedrine": "エフェドリン",
    "Cromoglicate": "クロモグリク酸",
    "Omalizumab": "オマリズマブ",
    "Mepolizumab": "メポリズマブ",
    "Benralizumab": "ベンラリズマブ",
    "Dupilumab": "デュピルマブ",

    # --- ステロイド ---
    "Prednisolone": "プレドニゾロン",
    "Dexamethasone": "デキサメタゾン",
    "Betamethasone": "ベタメタゾン",
    "Methylprednisolone": "メチルプレドニゾロン",
    "Hydrocortisone": "ヒドロコルチゾン",
    "Cortisone": "コルチゾン",
    "Triamcinolone": "トリアムシノロン",
    "Fludrocortisone": "フルドロコルチゾン",

    # --- 免疫抑制 ---
    "Tacrolimus": "タクロリムス",
    "Cyclosporine": "シクロスポリン",
    "Mycophenolate": "ミコフェノール酸",
    "Azathioprine": "アザチオプリン",
    "Methotrexate": "メトトレキサート",
    "Hydroxychloroquine": "ヒドロキシクロロキン",
    "Leflunomide": "レフルノミド",
    "Iguratimod": "イグラチモド",
    "Bucillamine": "ブシラミン",
    "Salazosulfapyridine": "サラゾスルファピリジン",

    # --- 生物学的製剤 ---
    "Adalimumab": "アダリムマブ",
    "Infliximab": "インフリキシマブ",
    "Etanercept": "エタネルセプト",
    "Tocilizumab": "トシリズマブ",
    "Sarilumab": "サリルマブ",
    "Golimumab": "ゴリムマブ",
    "Certolizumab": "セルトリズマブ",
    "Abatacept": "アバタセプト",
    "Ustekinumab": "ウステキヌマブ",
    "Secukinumab": "セクキヌマブ",
    "Ixekizumab": "イキセキズマブ",
    "Guselkumab": "グセルクマブ",
    "Risankizumab": "リサンキズマブ",
    "Vedolizumab": "ベドリズマブ",

    # --- JAK阻害 ---
    "Baricitinib": "バリシチニブ",
    "Tofacitinib": "トファシチニブ",
    "Upadacitinib": "ウパダシチニブ",
    "Peficitinib": "ペフィシチニブ",
    "Filgotinib": "フィルゴチニブ",

    # --- 抗菌薬 ペニシリン系 ---
    "Amoxicillin": "アモキシシリン",
    "Ampicillin": "アンピシリン",
    "Piperacillin": "ピペラシリン",
    "Sultamicillin": "スルタミシリン",
    "Benzylpenicillin": "ベンジルペニシリン",
    "Penicillin": "ペニシリン",

    # --- セフェム系 ---
    "Cefazolin": "セファゾリン",
    "Cefditoren": "セフジトレン",
    "Ceftriaxone": "セフトリアキソン",
    "Cefepime": "セフェピム",
    "Cefmetazole": "セフメタゾール",
    "Cefotaxime": "セフォタキシム",
    "Ceftazidime": "セフタジジム",
    "Cefcapene": "セフカペン",
    "Cefpodoxime": "セフポドキシム",
    "Cephalexin": "セファレキシン",
    "Cefozopran": "セフォゾプラン",
    "Cefaclor": "セファクロル",
    "Flomoxef": "フロモキセフ",

    # --- カルバペネム系 ---
    "Meropenem": "メロペネム",
    "Imipenem": "イミペネム",
    "Doripenem": "ドリペネム",
    "Biapenem": "ビアペネム",

    # --- マクロライド系 ---
    "Clarithromycin": "クラリスロマイシン",
    "Azithromycin": "アジスロマイシン",
    "Erythromycin": "エリスロマイシン",
    "Roxithromycin": "ロキシスロマイシン",
    "Josamycin": "ジョサマイシン",

    # --- ニューキノロン系 ---
    "Levofloxacin": "レボフロキサシン",
    "Moxifloxacin": "モキシフロキサシン",
    "Ciprofloxacin": "シプロフロキサシン",
    "Sitafloxacin": "シタフロキサシン",
    "Garenoxacin": "ガレノキサシン",
    "Tosufloxacin": "トスフロキサシン",
    "Norfloxacin": "ノルフロキサシン",
    "Ofloxacin": "オフロキサシン",
    "Prulifloxacin": "プルリフロキサシン",

    # --- その他抗菌 ---
    "Vancomycin": "バンコマイシン",
    "Teicoplanin": "テイコプラニン",
    "Linezolid": "リネゾリド",
    "Daptomycin": "ダプトマイシン",
    "Gentamicin": "ゲンタマイシン",
    "Amikacin": "アミカシン",
    "Tobramycin": "トブラマイシン",
    "Minocycline": "ミノサイクリン",
    "Doxycycline": "ドキシサイクリン",
    "Tetracycline": "テトラサイクリン",
    "Tigecycline": "チゲサイクリン",
    "Trimethoprim": "トリメトプリム",
    "Sulfamethoxazole": "スルファメトキサゾール",
    "Fosfomycin": "ホスホマイシン",
    "Clindamycin": "クリンダマイシン",
    "Metronidazole": "メトロニダゾール",
    "Colistin": "コリスチン",
    "Polymyxin": "ポリミキシン",
    "Rifampicin": "リファンピシン",
    "Isoniazid": "イソニアジド",
    "Pyrazinamide": "ピラジナミド",
    "Ethambutol": "エタンブトール",

    # --- 抗真菌 ---
    "Fluconazole": "フルコナゾール",
    "Itraconazole": "イトラコナゾール",
    "Voriconazole": "ボリコナゾール",
    "Posaconazole": "ポサコナゾール",
    "Micafungin": "ミカファンギン",
    "Caspofungin": "カスポファンギン",
    "Amphotericin": "アムホテリシン",
    "Terbinafine": "テルビナフィン",
    "Flucytosine": "フルシトシン",

    # --- 抗ウイルス ---
    "Acyclovir": "アシクロビル",
    "Valacyclovir": "バラシクロビル",
    "Oseltamivir": "オセルタミビル",
    "Baloxavir": "バロキサビル",
    "Laninamivir": "ラニナミビル",
    "Zanamivir": "ザナミビル",
    "Remdesivir": "レムデシビル",
    "Favipiravir": "ファビピラビル",
    "Ribavirin": "リバビリン",
    "Sofosbuvir": "ソホスブビル",
    "Ledipasvir": "レジパスビル",
    "Glecaprevir": "グレカプレビル",
    "Pibrentasvir": "ピブレンタスビル",
    "Entecavir": "エンテカビル",
    "Tenofovir": "テノホビル",
    "Lamivudine": "ラミブジン",
    "Adefovir": "アデホビル",
    "Ganciclovir": "ガンシクロビル",

    # --- 抗腫瘍 分子標的 ---
    "Imatinib": "イマチニブ",
    "Gefitinib": "ゲフィチニブ",
    "Erlotinib": "エルロチニブ",
    "Afatinib": "アファチニブ",
    "Osimertinib": "オシメルチニブ",
    "Crizotinib": "クリゾチニブ",
    "Alectinib": "アレクチニブ",
    "Lorlatinib": "ロルラチニブ",
    "Sunitinib": "スニチニブ",
    "Sorafenib": "ソラフェニブ",
    "Lenvatinib": "レンバチニブ",
    "Regorafenib": "レゴラフェニブ",
    "Cabozantinib": "カボザンチニブ",
    "Axitinib": "アキシチニブ",
    "Pazopanib": "パゾパニブ",
    "Dabrafenib": "ダブラフェニブ",
    "Trametinib": "トラメチニブ",
    "Vemurafenib": "ベムラフェニブ",
    "Ibrutinib": "イブルチニブ",
    "Acalabrutinib": "アカラブルチニブ",
    "Ruxolitinib": "ルキソリチニブ",
    "Palbociclib": "パルボシクリブ",
    "Ribociclib": "リボシクリブ",
    "Abemaciclib": "アベマシクリブ",
    "Olaparib": "オラパリブ",
    "Niraparib": "ニラパリブ",
    "Everolimus": "エベロリムス",
    "Temsirolimus": "テムシロリムス",
    "Bortezomib": "ボルテゾミブ",
    "Lenalidomide": "レナリドミド",
    "Pomalidomide": "ポマリドミド",
    "Thalidomide": "サリドマイド",

    # --- 免疫チェックポイント ---
    "Nivolumab": "ニボルマブ",
    "Pembrolizumab": "ペムブロリズマブ",
    "Atezolizumab": "アテゾリズマブ",
    "Durvalumab": "デュルバルマブ",
    "Avelumab": "アベルマブ",
    "Ipilimumab": "イピリムマブ",
    "Tremelimumab": "トレメリムマブ",

    # --- 抗体医薬 ---
    "Trastuzumab": "トラスツズマブ",
    "Bevacizumab": "ベバシズマブ",
    "Rituximab": "リツキシマブ",
    "Cetuximab": "セツキシマブ",
    "Panitumumab": "パニツムマブ",
    "Pertuzumab": "ペルツズマブ",
    "Ramucirumab": "ラムシルマブ",
    "Daratumumab": "ダラツムマブ",
    "Obinutuzumab": "オビヌツズマブ",
    "Mogamulizumab": "モガムリズマブ",

    # --- 殺細胞性抗がん薬 ---
    "Doxorubicin": "ドキソルビシン",
    "Epirubicin": "エピルビシン",
    "Cisplatin": "シスプラチン",
    "Carboplatin": "カルボプラチン",
    "Oxaliplatin": "オキサリプラチン",
    "Paclitaxel": "パクリタキセル",
    "Docetaxel": "ドセタキセル",
    "Fluorouracil": "フルオロウラシル",
    "Capecitabine": "カペシタビン",
    "Gemcitabine": "ゲムシタビン",
    "Irinotecan": "イリノテカン",
    "Etoposide": "エトポシド",
    "Cyclophosphamide": "シクロホスファミド",
    "Vincristine": "ビンクリスチン",
    "Vinblastine": "ビンブラスチン",
    "Pemetrexed": "ペメトレキセド",
    "Cytarabine": "シタラビン",
    "Bleomycin": "ブレオマイシン",
    "Mitomycin": "マイトマイシン",
    "Temozolomide": "テモゾロミド",

    # --- 支持療法 ---
    "Filgrastim": "フィルグラスチム",
    "Pegfilgrastim": "ペグフィルグラスチム",
    "Epoetin": "エポエチン",
    "Darbepoetin": "ダルベポエチン",
    "Eltrombopag": "エルトロンボパグ",
    "Romiplostim": "ロミプロスチム",
    "Leucovorin": "ロイコボリン",
    "Mesna": "メスナ",
    "Dexrazoxane": "デクスラゾキサン",

    # --- アレルギー ---
    "Fexofenadine": "フェキソフェナジン",
    "Cetirizine": "セチリジン",
    "Levocetirizine": "レボセチリジン",
    "Loratadine": "ロラタジン",
    "Desloratadine": "デスロラタジン",
    "Bilastine": "ビラスチン",
    "Olopatadine": "オロパタジン",
    "Epinastine": "エピナスチン",
    "Bepotastine": "ベポタスチン",
    "Rupatadine": "ルパタジン",
    "Azelastine": "アゼラスチン",
    "Ketotifen": "ケトチフェン",
    "Diphenhydramine": "ジフェンヒドラミン",
    "Chlorpheniramine": "クロルフェニラミン",
    "Hydroxyzine": "ヒドロキシジン",
    "Promethazine": "プロメタジン",

    # --- 泌尿器 ---
    "Tamsulosin": "タムスロシン",
    "Naftopidil": "ナフトピジル",
    "Silodosin": "シロドシン",
    "Dutasteride": "デュタステリド",
    "Finasteride": "フィナステリド",
    "Mirabegron": "ミラベグロン",
    "Vibegron": "ビベグロン",
    "Solifenacin": "ソリフェナシン",
    "Fesoterodine": "フェソテロジン",
    "Tolterodine": "トルテロジン",
    "Oxybutynin": "オキシブチニン",
    "Propiverine": "プロピベリン",
    "Imidafenacin": "イミダフェナシン",
    "Sildenafil": "シルデナフィル",
    "Tadalafil": "タダラフィル",
    "Vardenafil": "バルデナフィル",

    # --- 痛風・高尿酸 ---
    "Allopurinol": "アロプリノール",
    "Febuxostat": "フェブキソスタット",
    "Topiroxostat": "トピロキソスタット",
    "Benzbromarone": "ベンズブロマロン",
    "Probenecid": "プロベネシド",
    "Colchicine": "コルヒチン",
    "Dotinurad": "ドチヌラド",

    # --- 止血・血液 ---
    "Tranexamic acid": "トラネキサム酸",
    "Carbazochrome": "カルバゾクロム",

    # --- 血管拡張・末梢循環 ---
    "Alprostadil": "アルプロスタジル",
    "Limaprost": "リマプロスト",
    "Beraprost": "ベラプロスト",

    # --- 鉄剤 ---
    "Ferrous": "鉄",
    "Iron": "鉄",

    # --- 麻酔 ---
    "Propofol": "プロポフォール",
    "Ketamine": "ケタミン",
    "Sevoflurane": "セボフルラン",
    "Isoflurane": "イソフルラン",
    "Desflurane": "デスフルラン",
    "Thiopental": "チオペンタール",
    "Dexmedetomidine": "デクスメデトミジン",
    "Rocuronium": "ロクロニウム",
    "Sugammadex": "スガマデクス",
    "Droperidol": "ドロペリドール",
    "Remimazolam": "レミマゾラム",

    # --- 肺線維症 ---
    "Pirfenidone": "ピルフェニドン",
    "Nintedanib": "ニンテダニブ",

    # --- 肝疾患 ---
    "Ursodeoxycholic acid": "ウルソデオキシコール酸",

    # --- 無機化合物 ---
    "Magnesium oxide": "酸化マグネシウム",
    "Lithium carbonate": "炭酸リチウム",
    "Potassium chloride": "塩化カリウム",
    "Sodium chloride": "塩化ナトリウム",
    "Calcium carbonate": "炭酸カルシウム",
    "Glucose": "ブドウ糖",
    "Oxygen": "酸素",
    "Nitrous oxide": "亜酸化窒素",
    "Heparinoid": "ヘパリノイド",
    "Sennosides": "センノシド",

    # --- その他 ---
    "Nicotine": "ニコチン",
    "Alteplase": "アルテプラーゼ",
    "Epinephrine": "アドレナリン",
    "Noradrenaline": "ノルアドレナリン",
    "Dopamine": "ドパミン",
    "Dobutamine": "ドブタミン",
    "Pilocarpine": "ピロカルピン",
    "Atropine": "アトロピン",
    "Baclofen": "バクロフェン",
    "Tizanidine": "チザニジン",
    "Eperisone": "エペリゾン",
    "Dantrolene": "ダントロレン",
    "Dipyridamole": "ジピリダモール",
    "Sacubitril": "サクビトリル",
    "Colestyramine": "コレスチラミン",
    "Naldemedine": "ナルデメジン",


    # --- 追加分 ---
    "Abacavir": "アバカビル",
    "Acetazolamide": "アセタゾラミド",
    "Acoramidis": "アコラミジス",
    "Acotiamide": "アコチアミド",
    "Actinomycin": "アクチノマイシン",
    "Aflibercept": "アフリベルセプト",
    "Afloqualone": "アフロクアロン",
    "Agalsidase": "アガルシダーゼ",
    "Albumin": "アルブミン",
    "Alfentanil": "アルフェンタニル",
    "Alglucosidase": "アルグルコシダーゼ",
    "Alirocumab": "アリロクマブ",
    "Aliskiren": "アリスキレン",
    "Alvimopan": "アルビモパン",
    "Ambrisentan": "アンブリセンタン",
    "Amenamevir": "アメナメビル",
    "Amobarbital": "アモバルビタール",
    "Anagliptin": "アナグリプチン",
    "Anakinra": "アナキンラ",
    "Anifrolumab": "アニフロルマブ",
    "Apomorphine": "アポモルヒネ",
    "Argatroban": "アルガトロバン",
    "Arsenic": "亜ヒ酸",
    "Ascorbic": "アスコルビン酸",
    "Asenapine": "アセナピン",
    "Asparaginase": "アスパラギナーゼ",
    "Atazanavir": "アタザナビル",
    "Auranofin": "オーラノフィン",
    "Avatrombopag": "アバトロンボパグ",
    "Azacitidine": "アザシチジン",
    "Azasetron": "アザセトロン",
    "Belimumab": "ベリムマブ",
    "Bendamustine": "ベンダムスチン",
    "Bethanechol": "ベタネコール",
    "Bictegravir": "ビクテグラビル",
    "Bimatoprost": "ビマトプロスト",
    "Binimetinib": "ビニメチニブ",
    "Biotin": "ビオチン",
    "Bisacodyl": "ビサコジル",
    "Bosentan": "ボセンタン",
    "Brentuximab": "ブレンツキシマブ",
    "Brimonidine": "ブリモニジン",
    "Brineura": "ブリニューラ",
    "Brinzolamide": "ブリンゾラミド",
    "Brivaracetam": "ブリバラセタム",
    "Brolucizumab": "ブロルシズマブ",
    "Bromocriptine": "ブロモクリプチン",
    "Bunazosin": "ブナゾシン",
    "Bupivacaine": "ブピバカイン",
    "Buspirone": "ブスピロン",
    "Busulfan": "ブスルファン",
    "Butylscopolamine": "ブチルスコポラミン",
    "Cabazitaxel": "カバジタキセル",
    "Cabergoline": "カベルゴリン",
    "Calcipotriol": "カルシポトリオール",
    "Calcium": "カルシウム",
    "Camostat": "カモスタット",
    "Canakinumab": "カナキヌマブ",
    "Cannabidiol": "カンナビジオール",
    "Caplacizumab": "カプラシズマブ",
    "Capmatinib": "カプマチニブ",
    "Carfilzomib": "カルフィルゾミブ",
    "Cariprazine": "カリプラジン",
    "Cemiplimab": "セミプリマブ",
    "Cerliponase": "セルリポナーゼ",
    "Chloral": "抱水クロラール",
    "Chlorphenesin": "クロルフェネシン",
    "Cholecalciferol": "コレカルシフェロール",
    "Cidofovir": "シドホビル",
    "Cisatracurium": "シスアトラクリウム",
    "Cladribine": "クラドリビン",
    "Clonidine": "クロニジン",
    "Clorazepate": "クロラゼプ酸",
    "Cloxazolam": "クロキサゾラム",
    "Copper": "銅",
    "Cyanocobalamin": "シアノコバラミン",
    "Dacarbazine": "ダカルバジン",
    "Daikenchuto": "大建中湯",
    "Dapoxetine": "ダポキセチン",
    "Daprodustat": "ダプロデュスタット",
    "Darifenacin": "ダリフェナシン",
    "Darunavir": "ダルナビル",
    "Daunorubicin": "ダウノルビシン",
    "Decitabine": "デシタビン",
    "Dexlansoprazole": "デクスランソプラゾール",
    "Distigmine": "ジスチグミン",
    "Dolutegravir": "ドルテグラビル",
    "Dorzolamide": "ドルゾラミド",
    "Doxazosin": "ドキサゾシン",
    "Eculizumab": "エクリズマブ",
    "Efavirenz": "エファビレンツ",
    "Efinaconazole": "エフィナコナゾール",
    "Elosulfase": "エロスルファーゼ",
    "Elotuzumab": "エロツズマブ",
    "Elvitegravir": "エルビテグラビル",
    "Emicizumab": "エミシズマブ",
    "Emtricitabine": "エムトリシタビン",
    "Enasidenib": "エナシデニブ",
    "Encorafenib": "エンコラフェニブ",
    "Enfortumab": "エンホルツマブ",
    "Ensitrelvir": "エンシトレルビル",
    "Entrectinib": "エヌトレクチニブ",
    "Epalrestat": "エパルレスタット",
    "Epoprostenol": "エポプロステノール",
    "Ergocalciferol": "エルゴカルシフェロール",
    "Eribulin": "エリブリン",
    "Ertugliflozin": "エルツグリフロジン",
    "Esaxerenone": "エサキセレノン",
    "Esflurbiprofen": "エスフルルビプロフェン",
    "Esmolol": "エスモロール",
    "Ethosuximide": "エトスクシミド",
    "Evinacumab": "エビナクマブ",
    "Evolocumab": "エボロクマブ",
    "Faricimab": "ファリシマブ",
    "Fenfluramine": "フェンフルラミン",
    "Ferric": "鉄",
    "Fibrinogen": "フィブリノゲン",
    "Finerenone": "フィネレノン",
    "Flavoxate": "フラボキサート",
    "Floxuridine": "フロクスウリジン",
    "Fludarabine": "フルダラビン",
    "Fluphenazine": "フルフェナジン",
    "Flurazepam": "フルラゼパム",
    "Flutazolam": "フルタゾラム",
    "Folic acid": "葉酸",
    "Foscarnet": "ホスカルネット",
    "Fosphenytoin": "ホスフェニトイン",
    "Fusidic": "フシジン酸",
    "Gabexate": "ガベキサート",
    "Gilteritinib": "ギルテリチニブ",
    "Glasdegib": "グラスデギブ",
    "Glipizide": "グリピジド",
    "Guanfacine": "グアンファシン",
    "Haloxazolam": "ハロキサゾラム",
    "Hydralazine": "ヒドララジン",
    "Hydroxocobalamin": "ヒドロキソコバラミン",
    "Hydroxyurea": "ヒドロキシウレア",
    "Ibudilast": "イブジラスト",
    "Idarubicin": "イダルビシン",
    "Idursulfase": "イデュルスルファーゼ",
    "Ifosfamide": "イホスファミド",
    "Immunoglobulin": "免疫グロブリン",
    "Inclisiran": "インクリシラン",
    "Inotersen": "イノテルセン",
    "Interferon": "インターフェロン",
    "Iodine": "ヨウ素",
    "Isatuximab": "イサツキシマブ",
    "Ivabradine": "イバブラジン",
    "Ivosidenib": "イボシデニブ",
    "Ixazomib": "イキサゾミブ",
    "Lactulose": "ラクツロース",
    "Landiolol": "ランジオロール",
    "Lapatinib": "ラパチニブ",
    "Laronidase": "ラロニダーゼ",
    "Larotrectinib": "ラロトレクチニブ",
    "Latanoprost": "ラタノプロスト",
    "Levobupivacaine": "レボブピバカイン",
    "Levomepromazine": "レボメプロマジン",
    "Lopinavir": "ロピナビル",
    "Loxistilomab": "ロキシスチロマブ",
    "Luliconazole": "ルリコナゾール",
    "Lurasidone": "ルラシドン",
    "Luspatercept": "ルスパテルセプト",
    "Macitentan": "マシテンタン",
    "Macrogol": "マクロゴール",
    "Magnesium": "マグネシウム",
    "Mannitol": "マンニトール",
    "Maxacalcitol": "マキサカルシトール",
    "Mecobalamin": "メコバラミン",
    "Medazepam": "メダゼパム",
    "Melphalan": "メルファラン",
    "Menatetrenone": "メナテトレノン",
    "Mepivacaine": "メピバカイン",
    "Methocarbamol": "メトカルバモール",
    "Methyldopa": "メチルドパ",
    "Mexazolam": "メキサゾラム",
    "Midostaurin": "ミドスタウリン",
    "Migalastat": "ミガーラスタット",
    "Milrinone": "ミルリノン",
    "Minoxidil": "ミノキシジル",
    "Mitiglinide": "ミチグリニド",
    "Mitoxantrone": "ミトキサントロン",
    "Mizoribine": "ミゾリビン",
    "Moclobemide": "モクロベミド",
    "Molidustat": "モリデュスタット",
    "Molnupiravir": "モルヌピラビル",
    "Monteplase": "モンテプラーゼ",
    "Mupirocin": "ムピロシン",
    "Nab-paclitaxel": "ナブパクリタキセル",
    "Nadifloxacin": "ナジフロキサシン",
    "Nafamostat": "ナファモスタット",
    "Nateglinide": "ナテグリニド",
    "Nelarabine": "ネララビン",
    "Nemolizumab": "ネモリズマブ",
    "Neostigmine": "ネオスチグミン",
    "Neratinib": "ネラチニブ",
    "Nevirapine": "ネビラピン",
    "Niacin": "ナイアシン",
    "Nicotinamide": "ニコチンアミド",
    "Nimetazepam": "ニメタゼパム",
    "Nirmatrelvir": "ニルマトレルビル",
    "Nusinersen": "ヌシネルセン",
    "Olprinone": "オルプリノン",
    "Omarigliptin": "オマリグリプチン",
    "Onasemnogene": "オナセムノゲン",
    "Oxazolam": "オキサゾラム",
    "Pancuronium": "パンクロニウム",
    "Panobinostat": "パノビノスタット",
    "Pantoprazole": "パントプラゾール",
    "Pantothenic": "パントテン酸",
    "Patisiran": "パチシラン",
    "Pemirolast": "ペミロラスト",
    "Penicillamine": "ペニシラミン",
    "Pentobarbital": "ペントバルビタール",
    "Pergolide": "ペルゴリド",
    "Perphenazine": "ペルフェナジン",
    "Phosphate": "リン酸",
    "Phytonadione": "フィトナジオン",
    "Picosulfate": "ピコスルファート",
    "Pimozide": "ピモジド",
    "Pirenzepine": "ピレンゼピン",
    "Polatuzumab": "ポラツズマブ",
    "Polyethylene": "ポリエチレングリコール",
    "Potassium": "カリウム",
    "Pralsetinib": "プラルセチニブ",
    "Prazosin": "プラゾシン",
    "Pridinol": "プリジノール",
    "Primidone": "プリミドン",
    "Procaine": "プロカイン",
    "Procarbazine": "プロカルバジン",
    "Propantheline": "プロパンテリン",
    "Prucalopride": "プルカロプリド",
    "Pyridoxine": "ピリドキシン",
    "Raltegravir": "ラルテグラビル",
    "Ramosetron": "ラモセトロン",
    "Ranibizumab": "ラニビズマブ",
    "Ravulizumab": "ラブリズマブ",
    "Remifentanil": "レミフェンタニル",
    "Repaglinide": "レパグリニド",
    "Retapamulin": "レタパムリン",
    "Retinol": "レチノール",
    "Riboflavin": "リボフラビン",
    "Rikkunshito": "六君子湯",
    "Rilpivirine": "リルピビリン",
    "Riociguat": "リオシグアト",
    "Ripasudil": "リパスジル",
    "Ritonavir": "リトナビル",
    "Roflumilast": "ロフルミラスト",
    "Ropivacaine": "ロピバカイン",
    "Roxadustat": "ロキサデュスタット",
    "Rucaparib": "ルカパリブ",
    "Sacituzumab": "サシツズマブ",
    "Secobarbital": "セコバルビタール",
    "Selenium": "セレン",
    "Selexipag": "セレキシパグ",
    "Selinexor": "セリネクソル",
    "Selpercatinib": "セルペルカチニブ",
    "Sodium": "ナトリウム",
    "Sonidegib": "ソニデギブ",
    "Sorbitol": "ソルビトール",
    "Sufentanil": "スフェンタニル",
    "Suplatast": "スプラタスト",
    "Sutimlimab": "スチムリマブ",
    "Suxamethonium": "スキサメトニウム",
    "Tacalcitol": "タカルシトール",
    "Tafamidis": "タファミジス",
    "Tafluprost": "タフルプロスト",
    "Talazoparib": "タラゾパリブ",
    "Tamibarotene": "タミバロテン",
    "Tandospirone": "タンドスピロン",
    "Tegafur": "テガフール",
    "Tepotinib": "テポチニブ",
    "Terazosin": "テラゾシン",
    "Tetracaine": "テトラカイン",
    "Tezepelumab": "テゼペルマブ",
    "Thiamine": "チアミン",
    "Thiamylal": "チアミラール",
    "Thrombin": "トロンビン",
    "Timolol": "チモロール",
    "Tirzepatide": "チルゼパチド",
    "Tivozanib": "チボザニブ",
    "Tocopherol": "トコフェロール",
    "Tofisopam": "トフィソパム",
    "Tolperisone": "トルペリゾン",
    "Topotecan": "トポテカン",
    "Tranilast": "トラニラスト",
    "Travoprost": "トラボプロスト",
    "Treprostinil": "トレプロスチニル",
    "Tretinoin": "トレチノイン",
    "Triclofos": "トリクロホス",
    "Trifluridine": "トリフルリジン",
    "Tucatinib": "ツカチニブ",
    "Tucidinostat": "ツシジノスタット",
    "Ursodeoxycholic": "ウルソデオキシコール酸",
    "Vadadustat": "バダデュスタット",
    "Valproate": "バルプロ酸",
    "Vandetanib": "バンデタニブ",
    "Vecuronium": "ベクロニウム",
    "Venetoclax": "ベネトクラクス",
    "Vigabatrin": "ビガバトリン",
    "Vinorelbine": "ビノレルビン",
    "Vismodegib": "ビスモデギブ",
    "Vorinostat": "ボリノスタット",
    "Vutrisiran": "ブトリシラン",
    "Zanubrutinib": "ザヌブルチニブ",
    "Zinc": "亜鉛",
    "Zotepine": "ゾテピン",
}

# ============================================================
# 2. 接尾辞→カタカナ 変換ルール
# ============================================================
SUFFIX_RULES = [
    # 抗体医薬
    ("zumab", "ズマブ"),
    ("ximab", "キシマブ"),
    ("mumab", "ムマブ"),
    ("lumab", "ルマブ"),
    ("tumab", "ツマブ"),
    ("numab", "ヌマブ"),
    ("cumab", "クマブ"),
    # 分子標的
    ("tinib", "チニブ"),
    ("zanib", "ザニブ"),
    ("fenib", "フェニブ"),
    ("ciclib", "シクリブ"),
    ("parib", "パリブ"),
    # 消化器
    ("prazole", "プラゾール"),
    ("pridine", "プリジン"),
    # 脂質
    ("statin", "スタチン"),
    ("fibrate", "フィブラート"),
    # 降圧
    ("sartan", "サルタン"),
    ("dipine", "ジピン"),
    ("olol", "ロール"),
    ("pril", "プリル"),
    # 抗菌
    ("floxacin", "フロキサシン"),
    ("penem", "ペネム"),
    ("mycin", "マイシン"),
    ("cycline", "サイクリン"),
    ("cillin", "シリン"),
    ("azole", "アゾール"),
    ("fungin", "ファンギン"),
    # 抗ウイルス
    ("navir", "ナビル"),
    ("buvir", "ブビル"),
    ("asvir", "アスビル"),
    ("previr", "プレビル"),
    ("vudine", "ブジン"),
    # 糖尿病
    ("gliptin", "グリプチン"),
    ("gliflozin", "グリフロジン"),
    ("glutide", "グルチド"),
    # 免疫
    ("citinib", "シチニブ"),
    ("tinib", "チニブ"),
    ("limus", "リムス"),
    # 一般的語尾
    ("mab", "マブ"),
    ("nib", "ニブ"),
    ("lib", "リブ"),
    ("tide", "チド"),
    ("pine", "ピン"),
    ("pam", "パム"),
    ("lam", "ラム"),
    ("done", "ドン"),
    ("sone", "ゾン"),
    ("lone", "ロン"),
    ("tine", "チン"),
    ("dine", "ジン"),
    ("mine", "ミン"),
    ("zine", "ジン"),
    ("rine", "リン"),
    ("line", "リン"),
    ("ine", "イン"),
    ("ide", "イド"),
    ("ate", "エート"),
    ("ose", "オース"),
    ("ol", "オール"),
    ("il", "イル"),
    ("al", "アール"),
    ("an", "アン"),
    ("um", "ウム"),
    ("in", "イン"),
    ("on", "オン"),
    ("en", "エン"),
    ("er", "エル"),
    ("ax", "アクス"),
    ("ix", "イクス"),
    ("ox", "オクス"),
    ("ab", "アブ"),
    ("ib", "イブ"),
    ("ub", "ウブ"),
]


def extract_base_name(name_en: str) -> str:
    """英語名から基本名（最初の単語〜括弧前）を抽出"""
    # "Acetaminophen (JP18/USP)" → "Acetaminophen"
    # "Clopidogrel bisulfate (USP)" → "Clopidogrel"
    base = name_en.split('(')[0].strip()
    # 塩形や水和物のsuffix除去
    for suffix in [' hydrochloride', ' sodium', ' potassium', ' calcium',
                   ' maleate', ' fumarate', ' mesylate', ' besylate',
                   ' besilate', ' sulfate', ' phosphate', ' tartrate',
                   ' citrate', ' succinate', ' acetate', ' hydrate',
                   ' dihydrochloride', ' monohydrate', ' hemihydrate',
                   ' tosylate', ' tosilate', ' bromide', ' chloride',
                   ' nitrate', ' oxide', ' carbonate', ' bicarbonate',
                   ' gluconate', ' lactate', ' propionate', ' butyrate',
                   ' valerate', ' hexanoate', ' stearate', ' oleate',
                   ' palmitate', ' decanoate', ' enanthate',
                   ' alfa', ' beta', ' gamma', ' delta',
                   ' dimaleate', ' olamine', ' meglumine',
                   ' pivoxil', ' marboxil', ' proxetil', ' axetil',
                   ' medoxomil', ' etexilate', ' alafenamide',
                   ' disoproxil', ' mofetil', ' diacetyl']:
        if base.lower().endswith(suffix):
            base = base[:len(base) - len(suffix)].strip()
            break
    # 先頭単語のみ（複合名でない場合）
    words = base.split()
    if len(words) == 1:
        return words[0]
    # 複合名の場合はそのまま
    return base


def english_to_katakana(name_en: str) -> str:
    """英名→カタカナ変換"""
    base = extract_base_name(name_en)

    # 1. 辞書完全一致
    for key, val in MANUAL_JA.items():
        if key.lower() == base.lower():
            return val

    # 2. 辞書先頭一致（"Insulin glargine" → "Insulin" でマッチ）
    first_word = base.split()[0] if ' ' in base else ''
    if first_word:
        for key, val in MANUAL_JA.items():
            if key.lower() == first_word.lower():
                return val

    # 3. 辞書部分一致（名前に含まれるか）
    base_lower = base.lower()
    for key, val in MANUAL_JA.items():
        if base_lower.startswith(key.lower()):
            return val

    return ""


def main():
    for graph_path in GRAPH_FILES:
        if not graph_path.exists():
            print(f"SKIP: {graph_path}")
            continue

        with open(graph_path, encoding="utf-8") as f:
            graph = json.load(f)

        added = 0
        skipped = 0
        already = 0

        for node in graph["nodes"]:
            if node.get("type") != "drug":
                continue
            if node.get("name_ja"):
                already += 1
                continue

            name_en = node.get("name_en", "")
            if not name_en:
                skipped += 1
                continue

            ja = english_to_katakana(name_en)
            if ja:
                node["name_ja"] = ja
                added += 1
            else:
                skipped += 1

        with open(graph_path, "w", encoding="utf-8") as f:
            json.dump(graph, f, ensure_ascii=False)

        total = already + added + skipped
        print(f"{graph_path.name}: "
              f"既存={already}, +追加={added}, 未対応={skipped} "
              f"(計{total}, カバー率={(already+added)/total*100:.1f}%)")

    print("完了")


if __name__ == "__main__":
    main()
